name: Deployment audit

on:
  push:
    branches: ["main", "feature/analysis-repo-and-ci", "work"]
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install frontend dependencies
        working-directory: web/frontend
        run: npm install

      - name: Lint frontend
        working-directory: web/frontend
        run: npm run lint

      - name: Test frontend
        working-directory: web/frontend
        run: npm run test

      - name: Build frontend
        working-directory: web/frontend
        run: npm run build

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run backend unit tests
        run: python -m unittest discover web/backend/tests

      - name: Audit workflows and logs
        run: python tools/audit_deployment.py --check
